# Lenguaje de programación
language: python

# Versiones de Python
python:

    - "3.5.8" # ultima actualizacion en 2019
    - "3.6.9" # (version de desarrollo) ultima actualizacion en 2019
    - "3.7.0" # ultima actualizada en 2018
    - "3.7.5" # ultima actualizacion en 2019
    - "3.8.0" # ultima actualizacion en 2019

#Crea entorno virtual e instala dependencias
before_install:
    - make install

# Ejecutar test y test de cobertura
script:
    - make test
