
version: 2
jobs:
  build:
    docker:
      #imagen docker de python donde se va a ejecutar los siguientes pasos
      - image: circleci/python:3.7.5
    steps:
      - checkout
      #Instalamos las dependencias con make
      - run:
          name: instalar dependencias
          command: make install

      # Ejecutamos tests y tests de cobertura
      - run:
          name: Ejecutar tests
          command:  make test
