
version: 2
jobs:
  build:
    docker:
      #imagen docker de python donde se va a ejecutar los siguientes pasos
      - image: circleci/python:3.6.9
      #imagen mongodb para las pruebas
      - image: mongo:3.6.3
    steps:
      - checkout
      # descargamos las dependencias de la cache
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Pipfile.lock" }} #fichero con dependencias al usar pipenv en el make
            - v1-dependencies- #comprobación mas generica de la cache

      #Instalamos las dependencias y creamos entorno virtual con make
      - run:
          name: instalar dependencias
          command: make install

      # Ejecutamos tests y tests de cobertura
      - run:
          name: Ejecutar tests
          command: make test

      - save_cache:
          paths:
           - ~/.local/share/virtualenvs/venv #ruta por defecto del entorno virtual
          key: v1-dependencies-{{ checksum "Pipfile.lock" }} #se usa la misma llave para guardar la cache 
